@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mustapelto.deepmoblearning.common.metadata;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;