@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mustapelto.deepmoblearning.common.entities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;