@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mustapelto.deepmoblearning.common;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;