@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mustapelto.deepmoblearning.common.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;